# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AppPackage < Formula
  desc "app-package official Homebrew distribution!"
  homepage "https://github.com/mas2020-golang/app-package"
  version "0.1.0-rc.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mas2020-golang/app-package/releases/download/v0.1.0-rc.1/app-package_0.1.0-rc.1_Darwin_arm64.tar.gz"
      sha256 "e5e3b517f713176f1c0dbe157bfd5f4c5c04617d64f57998d45945dee6604b8b"

      def install
        bin.install "app-package"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/app-package/releases/download/v0.1.0-rc.1/app-package_0.1.0-rc.1_Darwin_x86_64.tar.gz"
      sha256 "55f01c614c12c2ea434738584bf6b39a808daa79bac10d322269c4bff797e322"

      def install
        bin.install "app-package"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mas2020-golang/app-package/releases/download/v0.1.0-rc.1/app-package_0.1.0-rc.1_Linux_arm64.tar.gz"
      sha256 "8bcbf0b6af399ca74c1a9dce2c03fcddef3424c9038552d00361a436c41e15ed"

      def install
        bin.install "app-package"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/app-package/releases/download/v0.1.0-rc.1/app-package_0.1.0-rc.1_Linux_x86_64.tar.gz"
      sha256 "9baa63b367be2543627c7fc689067dcb2000c9a320f621db85fbfe5577856531"

      def install
        bin.install "app-package"
      end
    end
  end
end
